In [7]:
# read .npy file

import numpy as np

data = np.load('pixel_counts/crack500_s_pixel_counts.npy')

print(data.shape)
print(data)

(1785, 2)
[[158480   1520]
 [159271    729]
 [147941  12059]
 ...
 [159440    560]
 [158820   1180]
 [154663   5337]]


In [3]:
# gtFine version
import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/gtFine'

# 클래스별 픽셀 개수를 저장할 빈 NumPy 배열 생성
class_pixel_counts = []

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

size = (448,448)

# 각 하위 폴더에서 이미지 처리
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # PNG 파일만 선택
    files = [f for f in file_list if f.startswith('CFD') or f.startswith('GAPS')]
    print(len(files))

    # 클래스별 픽셀 개수 계산 및 저장
    for file in files:
        # 이미지 열기
        image = Image.open(os.path.join(subfolder_path, file))
        image = image.resize(size, Image.NEAREST)

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        # 각 클래스별 픽셀 개수 세기
        class_pixel_count = np.bincount(img_array.ravel(), minlength=2)  # 256은 픽셀 값 범위 (0-255)

        # 클래스별 픽셀 개수를 class_pixel_counts에 추가
        class_pixel_counts.append(class_pixel_count)

    print(len(class_pixel_counts))

# class_pixel_counts를 NumPy 배열로 변환
result_array = np.array(class_pixel_counts)

# 결과를 .npy 파일로 저장
# np.save('pixel_counts/cfd_target_pixel_counts.npy', result_array)

533
533
94
627


In [5]:
result_array.shape

(627, 2)

In [6]:
result_array

array([[194153,   6551],
       [197552,   3152],
       [198060,   2644],
       ...,
       [194566,   6138],
       [199332,   1372],
       [198806,   1898]])

In [11]:
np.save('/home/user/weak-da-seg-new/weak-da-seg/pixel_counts/road_t_pixel_counts.npy', result_array)

In [13]:
# leftImg8bit version
import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/02. Training&Test/013. General Concrete Damage/01. Cityscapes/v_bh/leftImg8bit'

# 클래스별 픽셀 개수를 저장할 빈 NumPy 배열 생성
class_pixel_counts = []

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

size = (1024,1024)

# 각 하위 폴더에서 이미지 처리
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # 파일 선택
    png_files = [f for f in file_list if f.endswith('_leftImg8bit.png')]
    print(len(png_files))

    subfolder_path = subfolder_path.replace('leftImg8bit', 'gtFine')
    # print(subfolder_path)

    # 클래스별 픽셀 개수 계산 및 저장
    for png_file in png_files:
        # 이미지 열기
        png_file = png_file.replace('_leftImg8bit.png', '_gtFine_labelIds.png')
        image = Image.open(os.path.join(subfolder_path, png_file))
        image = image.resize(size, Image.NEAREST)

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        # Mask out the class 255
        masked_array = np.where(img_array == 255, 0, img_array)

        # 각 클래스별 픽셀 개수 세기
        class_pixel_count = np.bincount(masked_array.ravel(), minlength=5)  # 256은 픽셀 값 범위 (0-255)

        # 클래스별 픽셀 개수를 class_pixel_counts에 추가
        class_pixel_counts.append(class_pixel_count)

# class_pixel_counts를 NumPy 배열로 변환
result_array = np.array(class_pixel_counts)

print(result_array.shape)

1902
482
(2384, 5)


In [14]:
result_array

array([[1047163,    1413,       0,       0,       0],
       [1046194,    2382,       0,       0,       0],
       [1046179,    2397,       0,       0,       0],
       ...,
       [1039675,    8901,       0,       0,       0],
       [1045663,    2913,       0,       0,       0],
       [1044725,    3851,       0,       0,       0]])

In [19]:
np.save('/home/user/weak-da-seg-new/weak-da-seg/pixel_counts/generalcon_t_pixel_counts.npy', result_array)